language: rust
cache:
    directories:
        - ./target
        - /home/travis/.cargo

os: linux
dist: bionic
addons:
    apt:
        packages:
            - libssl-dev
rust:
  - stable
before_script:
  - rustup component add clippy
  - cargo install cargo-tarpaulin
  - rustup target add wasm32-unknown-unknown
script:
  - cargo clippy -- -D clippy::all || travis_terminate 1
  - chmod +x ./build.sh
  - ./build.sh
after_success:
  - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
