[workspace]
members = [
    "core",
    "bip32",
    "bitcoin",
    "litecoin",
    "psbt",
    "provider",
]

exclude = [
  "bitcoin-wasm",  # Exluded so we can specify optimizer flags
  "ledger",  # Excluded until we can figure out how to build hidapi on travis
  "ledger-btc", # Excluded until we can figure out how to build hidapi on travis
]
