[package]
name = "provider"
version = "0.1.0"
authors = ["James Prestwich <james@prestwi.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.36"

futures-core = { version = "0.3.5", default-features = false }
futures-util = { version = "0.3.5", default-features = false }
futures-timer = "3.0.2"
pin-project = { version = "0.4.20", default-features = false }

riemann-core = { path = "../core" }
rmn-btc = { path = "../bitcoin" }

# esplora cache
lru = { version = "0.5.2", optional = true }
thiserror = { version = "1.0", optional = true }
futures = { version = "0.3.5", optional = true }
reqwest = { version = "0.10.4", features = ["json"], optional = true }
hex = { version = "0.4.2", optional = true }
serde = { version = "1.0.106", features = ["derive"], optional = true }

[features]
default = ["mainnet", "esplora"]
esplora = ["lru", "reqwest", "thiserror", "futures", "hex", "serde"]

# mutually exclusive
mainnet = ["rmn-btc/mainnet"]
testnet = ["rmn-btc/testnet"]
